/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.ClienteDAO;
import dao.MedicamentoDAO;
import dao.PedidoDAO;
import entity.Cliente;
import entity.Medicamento;
import entity.Pedido;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class ViewPedido extends javax.swing.JFrame {

    /**
     * Creates new form ViewPedido
     */
    public void Listar() {
        try {
            PedidoDAO pedidoDAO = new PedidoDAO();
            List<Pedido> pedido = pedidoDAO.listarPedidos();

            DefaultTableModel model = (DefaultTableModel) tabela.getModel();
            model.setNumRows(0);

            for (Pedido p : pedido) {
                model.addRow(new Object[]{
                    p.getIdPedido(),
                    p.getIdCliente(),
                    p.getIdMedicamento(),
                    p.getQtdeMedicamento(),
                    p.getDia()
                });
            }
        } catch (Exception e) {
            e.getMessage();
        }
    }

    public ViewPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jcMedicamento = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jtQtde = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcCliente = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jtData = new javax.swing.JTextField();
        jbAdicionar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        voltar = new javax.swing.JButton();
        jtID1 = new javax.swing.JLabel();
        voltar1 = new javax.swing.JButton();
        jtID = new javax.swing.JLabel();
        jtID2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Efetuar Pedido");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 180, 30));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcMedicamento.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jcMedicamentoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(jcMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 220, 30));

        jLabel3.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Quantidade:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, 20));
        jPanel1.add(jtQtde, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 100, 30));

        jLabel4.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Medicamento:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 110, 20));

        jcCliente.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jcClienteAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(jcCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 220, 30));

        jLabel5.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Data:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        jtData.setText("0000-00-00");
        jPanel1.add(jtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 160, 30));

        jbAdicionar.setBackground(new java.awt.Color(255, 102, 102));
        jbAdicionar.setForeground(new java.awt.Color(255, 255, 255));
        jbAdicionar.setText("Adicionar");
        jbAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdicionarActionPerformed(evt);
            }
        });
        jPanel1.add(jbAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        jbEditar.setBackground(new java.awt.Color(255, 102, 102));
        jbEditar.setForeground(new java.awt.Color(255, 255, 255));
        jbEditar.setText("Editar");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jbEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 81, -1));

        jbExcluir.setBackground(new java.awt.Color(255, 102, 102));
        jbExcluir.setForeground(new java.awt.Color(255, 255, 255));
        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(jbExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 81, -1));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cliente", "Medicamento", "Qtde", "Data"
            }
        ));
        tabela.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabelaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 568, 208));

        jLabel6.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Cliente:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        jLabel7.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jLabel7.setText("ID:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        voltar.setBackground(new java.awt.Color(255, 102, 102));
        voltar.setForeground(new java.awt.Color(255, 255, 255));
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        jPanel1.add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 70, -1));

        jtID1.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jtID1.setText("autoIncrement");
        jPanel1.add(jtID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 689, 480));

        voltar1.setBackground(new java.awt.Color(255, 102, 102));
        voltar1.setFont(new java.awt.Font("SimSun-ExtB", 0, 12)); // NOI18N
        voltar1.setForeground(new java.awt.Color(255, 255, 255));
        voltar1.setText("OK");
        voltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar1ActionPerformed(evt);
            }
        });
        getContentPane().add(voltar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 50, -1));

        jtID.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jtID.setText("Nome - telefone");
        getContentPane().add(jtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, -1, -1));

        jtID2.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jtID2.setText("Lista de Pedidos");
        getContentPane().add(jtID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("SimSun-ExtB", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 50, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicionarActionPerformed
        if (jtData.getText().isEmpty() | jtQtde.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Insira todos os dados");
        } else {
            String dia = jtData.getText();
            int qtde = Integer.parseInt(jtQtde.getText());

            Pedido pedido = new Pedido();
            Cliente c = new Cliente();
            Medicamento m = new Medicamento();

            pedido.setDia(dia);
            pedido.setQtdeMedicamento(qtde);
            //combo box
            c = (Cliente) jcCliente.getSelectedItem();
            m = (Medicamento) jcMedicamento.getSelectedItem();

            pedido.setIdCliente(c);
            pedido.setIdMedicamento(m);

            PedidoDAO pedidoDAO = new PedidoDAO();
            pedidoDAO.inserir(pedido);

            jtData.setText("");
            jtQtde.setText("");
            jcCliente.setSelectedIndex(0);
            jcMedicamento.setSelectedIndex(0);
        }

        Listar();
    }//GEN-LAST:event_jbAdicionarActionPerformed

    private void tabelaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabelaAncestorAdded

    }//GEN-LAST:event_tabelaAncestorAdded

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Listar();
    }//GEN-LAST:event_formWindowOpened

    private void jcClienteAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jcClienteAncestorAdded
        ClienteDAO dao = new ClienteDAO();
        List<Cliente> lista = dao.listarClientes();

        jcCliente.removeAllItems();

        for (Cliente c : lista) {
            jcCliente.addItem(c);
        }
    }//GEN-LAST:event_jcClienteAncestorAdded

    private void jcMedicamentoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jcMedicamentoAncestorAdded
        MedicamentoDAO dao = new MedicamentoDAO();
        List<Medicamento> lista = dao.listarMedicamentos();

        jcMedicamento.removeAllItems();

        for (Medicamento m : lista) {
            jcMedicamento.addItem(m);
        }
    }//GEN-LAST:event_jcMedicamentoAncestorAdded

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        if (jtData.getText().isEmpty() | jtQtde.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Insira todos os dados");
        } else {
            String dia = jtData.getText();
            int qtde = Integer.parseInt(jtQtde.getText());

            Pedido pedido = new Pedido();
            Cliente c = new Cliente();
            Medicamento m = new Medicamento();

            pedido.setDia(dia);
            pedido.setQtdeMedicamento(qtde);
            //combo box
            c = (Cliente) jcCliente.getSelectedItem();
            m = (Medicamento) jcMedicamento.getSelectedItem();

            pedido.setIdCliente(c);
            pedido.setIdMedicamento(m);

            PedidoDAO pedidoDAO = new PedidoDAO();
            pedidoDAO.inserir(pedido);

            jtData.setText("");
            jtQtde.setText("");
            jcCliente.setSelectedIndex(0);
            jcMedicamento.setSelectedIndex(0);
        }

        Listar();
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        try {
            Pedido pedido = new Pedido();

            pedido.setIdPedido(Integer.parseInt(jtID.getText()));

            PedidoDAO dao = new PedidoDAO();
            dao.excluir(pedido);

            JOptionPane.showMessageDialog(null, "Dados excluidos com sucesso.");
            Listar();

            jtData.setText("0000-00-00");
            jtQtde.setText("");
            jtID.setText("null");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao excluir os dados.");
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        jtID.setText(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
        jtQtde.setText(tabela.getValueAt(tabela.getSelectedRow(), 3).toString());
        jtData.setText(tabela.getValueAt(tabela.getSelectedRow(), 4).toString());
    }//GEN-LAST:event_tabelaMouseClicked

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        menuPrincipal obj = new menuPrincipal();
        obj.setLocationRelativeTo(obj);
        obj.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void voltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar1ActionPerformed
        // TODO add your handling code here:
        viewListaPedidos obj = new viewListaPedidos();
        obj.setLocationRelativeTo(obj);
        obj.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_voltar1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        viewNomeTelefone obj = new viewNomeTelefone();
        obj.setLocationRelativeTo(obj);
        obj.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewPedido obj = new ViewPedido();
                obj.setLocationRelativeTo(obj);
                obj.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAdicionar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JComboBox jcCliente;
    private javax.swing.JComboBox jcMedicamento;
    private javax.swing.JTextField jtData;
    private javax.swing.JLabel jtID;
    private javax.swing.JLabel jtID1;
    private javax.swing.JLabel jtID2;
    private javax.swing.JTextField jtQtde;
    private javax.swing.JTable tabela;
    private javax.swing.JButton voltar;
    private javax.swing.JButton voltar1;
    // End of variables declaration//GEN-END:variables
}
