/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.ClienteDAO;
import entity.Cliente;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class ViewCliente extends javax.swing.JFrame {

    /**
     * Creates new form ViewCliente
     */
    public void Listar() {
        try {
            ClienteDAO clienteDAO = new ClienteDAO();
            List<Cliente> cliente = clienteDAO.listarClientes();

            DefaultTableModel model = (DefaultTableModel) tabela.getModel();
            model.setNumRows(0);

            for (Cliente c : cliente) {
                model.addRow(new Object[]{
                    c.getIdCliente(),
                    c.getNome(),
                    c.getTelefone(),
                    c.getCpf(),
                    c.getBairro(),
                    c.getRua(),
                    c.getNumero()
                });
            }

        } catch (Exception e) {

        }
    }

    public ViewCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtCpf = new javax.swing.JTextField();
        jtTelefone = new javax.swing.JTextField();
        jbAdicionar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jtRua = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtBairro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtNumero = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtIDcliente1 = new javax.swing.JLabel();
        voltar = new javax.swing.JButton();
        voltar1 = new javax.swing.JButton();
        jtIDcliente = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Adicionar cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Nome:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));
        jPanel1.add(jtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 28, 430, -1));

        jLabel3.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Telefone:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("CPF:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));
        jPanel1.add(jtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 180, -1));

        jtTelefone.setText("+55");
        jPanel1.add(jtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 65, 430, -1));

        jbAdicionar.setBackground(new java.awt.Color(255, 102, 102));
        jbAdicionar.setForeground(new java.awt.Color(255, 255, 255));
        jbAdicionar.setText("Adicionar");
        jbAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdicionarActionPerformed(evt);
            }
        });
        jPanel1.add(jbAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 86, -1));

        jbEditar.setBackground(new java.awt.Color(255, 102, 102));
        jbEditar.setForeground(new java.awt.Color(255, 255, 255));
        jbEditar.setText("Editar");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jbEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 86, 50));

        jbExcluir.setBackground(new java.awt.Color(255, 102, 102));
        jbExcluir.setForeground(new java.awt.Color(255, 255, 255));
        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(jbExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 86, -1));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Telefone", "CPF", "Bairro", "Rua", "Número"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabela);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 630, 158));

        jLabel5.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Rua:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));
        jPanel1.add(jtRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 180, -1));

        jLabel6.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Bairro:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        jtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtBairroActionPerformed(evt);
            }
        });
        jPanel1.add(jtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 170, -1));

        jLabel7.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("Numero:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));
        jPanel1.add(jtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 182, -1));

        jLabel9.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("ID:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        jtIDcliente1.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jtIDcliente1.setForeground(new java.awt.Color(0, 0, 255));
        jtIDcliente1.setText("autoIncrement");
        jPanel1.add(jtIDcliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 740, -1));

        voltar.setBackground(new java.awt.Color(255, 102, 102));
        voltar.setForeground(new java.awt.Color(255, 255, 255));
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, -1, -1));

        voltar1.setBackground(new java.awt.Color(255, 102, 102));
        voltar1.setForeground(new java.awt.Color(255, 255, 255));
        voltar1.setText("OK");
        voltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar1ActionPerformed(evt);
            }
        });
        getContentPane().add(voltar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, -1, -1));

        jtIDcliente.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jtIDcliente.setForeground(new java.awt.Color(0, 0, 255));
        jtIDcliente.setText("Cliente - medicamento");
        getContentPane().add(jtIDcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicionarActionPerformed

        String nome = jtNome.getText();
        String telefone = jtTelefone.getText();
        String cpf = jtCpf.getText();
        String bairro = jtBairro.getText();
        String rua = jtRua.getText();
        int numero = Integer.parseInt(jtNumero.getText());

        Cliente cliente = new Cliente();
        cliente.setNome(nome);
        cliente.setTelefone(telefone);
        cliente.setCpf(cpf);
        cliente.setBairro(bairro);
        cliente.setRua(rua);
        cliente.setNumero(numero);

        ClienteDAO clienteDAO = new ClienteDAO();
        clienteDAO.inserir(cliente);

        jtNome.setText("");
        jtTelefone.setText("");
        jtCpf.setText("");
        jtBairro.setText("");
        jtRua.setText("");
        jtNumero.setText("");

        Listar();


    }//GEN-LAST:event_jbAdicionarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // listando dados na tabela
        Listar();


    }//GEN-LAST:event_formWindowOpened

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked

        jtIDcliente.setText(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
        jtNome.setText(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());
        jtTelefone.setText(tabela.getValueAt(tabela.getSelectedRow(), 2).toString());
        jtCpf.setText(tabela.getValueAt(tabela.getSelectedRow(), 3).toString());
        jtBairro.setText(tabela.getValueAt(tabela.getSelectedRow(), 4).toString());
        jtRua.setText(tabela.getValueAt(tabela.getSelectedRow(), 5).toString());
        jtNumero.setText(tabela.getValueAt(tabela.getSelectedRow(), 6).toString());

    }//GEN-LAST:event_tabelaMouseClicked

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        try {
            Cliente cliente = new Cliente();

            cliente.setIdCliente(Integer.parseInt(jtIDcliente.getText()));

            ClienteDAO clienteDAO = new ClienteDAO();
            clienteDAO.excluir(cliente);

            JOptionPane.showMessageDialog(null, "Dados excluidos com sucesso.");
            Listar();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao excluir os dados.");
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed

        String nome = jtNome.getText();
        String telefone = jtTelefone.getText();
        String cpf = jtCpf.getText();
        String bairro = jtBairro.getText();
        String rua = jtRua.getText();
        int numero = Integer.parseInt(jtNumero.getText());
        int id = Integer.parseInt(jtIDcliente.getText());

        try {
            Cliente cliente = new Cliente();

            cliente.setNome(nome);
            cliente.setTelefone(telefone);
            cliente.setCpf(cpf);
            cliente.setBairro(bairro);
            cliente.setRua(rua);
            cliente.setNumero(numero);
            cliente.setIdCliente(id);

            ClienteDAO clienteDAO = new ClienteDAO();
            clienteDAO.editar(cliente);

            JOptionPane.showMessageDialog(null, "Dados editados com sucesso.");
            Listar();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao editar os dados." + e);
        }
    }//GEN-LAST:event_jbEditarActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        menuPrincipal obj = new menuPrincipal();
        obj.setLocationRelativeTo(obj);
        obj.setVisible(true);
        this.setVisible(false);
        this.dispose();

    }//GEN-LAST:event_voltarActionPerformed

    private void jtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtBairroActionPerformed

    private void voltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar1ActionPerformed
        // TODO add your handling code here:
        viewMedCliente obj = new viewMedCliente();
        obj.setLocationRelativeTo(obj);
        obj.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_voltar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewCliente obj = new ViewCliente();
                obj.setLocationRelativeTo(obj);
                obj.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbAdicionar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JTextField jtBairro;
    private javax.swing.JTextField jtCpf;
    private javax.swing.JLabel jtIDcliente;
    private javax.swing.JLabel jtIDcliente1;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtNumero;
    private javax.swing.JTextField jtRua;
    private javax.swing.JTextField jtTelefone;
    private javax.swing.JTable tabela;
    private javax.swing.JButton voltar;
    private javax.swing.JButton voltar1;
    // End of variables declaration//GEN-END:variables
}
