/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.FornecedorDAO;
import entity.Fornecedor;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class ViewFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form ViewFornecedor
     */
        public void Listar(){
        try{
            FornecedorDAO fornecedorDAO = new FornecedorDAO();
            List<Fornecedor> fornecedor = fornecedorDAO.listarFornecedores();
            
            
            DefaultTableModel model = (DefaultTableModel)tabela.getModel();
            model.setNumRows(0);
            
            for(Fornecedor f : fornecedor){
                model.addRow(new Object[]{
                    f.getIdFornecedor(),
                    f.getCnpj(),
                    f.getNome(),
                    f.getTelefone(),
                    f.getEmail(),
                    f.getBairro(),
                    f.getRua(),
                    f.getNumero()
                });
            }
        } catch (Exception e){
            e.getMessage();
        }
    }
    
    
    
    
    public ViewFornecedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBadicionar = new javax.swing.JButton();
        jtCnpj = new javax.swing.JTextField();
        jtNome = new javax.swing.JTextField();
        jtEmail = new javax.swing.JTextField();
        jtExcluir = new javax.swing.JButton();
        jtEditar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtTelefone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtRua = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtNumero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtBairro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jtID = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Adicionar fornecedor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jPanel1.setPreferredSize(new java.awt.Dimension(640, 480));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("CNPJ:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Bairro:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Nome:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jBadicionar.setText("Adicionar");
        jBadicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBadicionarActionPerformed(evt);
            }
        });
        jPanel1.add(jBadicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, -1, -1));
        jPanel1.add(jtCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 470, -1));
        jPanel1.add(jtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 470, -1));
        jPanel1.add(jtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 470, -1));

        jtExcluir.setText("Excluir");
        jtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(jtExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 81, -1));

        jtEditar.setText("Editar");
        jtEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jtEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 81, 60));

        jLabel5.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Telefone:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));
        jPanel1.add(jtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 470, -1));

        jLabel6.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Email:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));
        jPanel1.add(jtRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 220, -1));

        jLabel7.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("Rua:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));
        jPanel1.add(jtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 187, -1));

        jLabel8.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("Número:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));
        jPanel1.add(jtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 187, -1));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CNPJ", "Nome", "Telefone", "Email", "Bairro", "Rua", "Número"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 660, 155));

        jLabel9.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 204));
        jLabel9.setText("ID:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        jtID.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jtID.setForeground(new java.awt.Color(0, 0, 204));
        jtID.setText("autoIncrement");
        jPanel1.add(jtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 80, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 760, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBadicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBadicionarActionPerformed
        String cnpj = jtCnpj.getText();
        String nome = jtNome.getText();
        String telefone = jtTelefone.getText();
        String email = jtEmail.getText();
        String bairro = jtBairro.getText();
        String rua = jtRua.getText();
        int num = Integer.parseInt(jtNumero.getText());
  
                
        Fornecedor fornecedor = new Fornecedor();
        fornecedor.setCnpj(cnpj);
        fornecedor.setNome(nome);
        fornecedor.setTelefone(telefone);
        fornecedor.setEmail(email);
        fornecedor.setBairro(bairro);
        fornecedor.setRua(rua);
        fornecedor.setNumero(num);
        
        FornecedorDAO fornecedorDAO = new FornecedorDAO();
        fornecedorDAO.inserir(fornecedor);
        
        jtCnpj.setText("");
        jtNome.setText("");
        jtTelefone.setText("");
        jtEmail.setText("");
        jtBairro.setText("");
        jtRua.setText("");
        jtNumero.setText("");
        jtID.setText("null");
        
        Listar();
    }//GEN-LAST:event_jBadicionarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        Listar();
    }//GEN-LAST:event_formWindowOpened

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        jtID.setText(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
        jtCnpj.setText(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());
        jtNome.setText(tabela.getValueAt(tabela.getSelectedRow(), 2).toString());
        jtTelefone.setText(tabela.getValueAt(tabela.getSelectedRow(), 3).toString());
        jtEmail.setText(tabela.getValueAt(tabela.getSelectedRow(), 4).toString());
        jtBairro.setText(tabela.getValueAt(tabela.getSelectedRow(), 5).toString());
        jtRua.setText(tabela.getValueAt(tabela.getSelectedRow(), 6).toString());
        jtNumero.setText(tabela.getValueAt(tabela.getSelectedRow(), 7).toString());
    }//GEN-LAST:event_tabelaMouseClicked

    private void jtEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtEditarActionPerformed
        int id = Integer.parseInt(jtID.getText());
        String cnpj = jtCnpj.getText();
        String nome = jtNome.getText();
        String telefone = jtTelefone.getText();
        String email = jtEmail.getText();
        String bairro = jtBairro.getText();
        String rua = jtRua.getText();
        int numero = Integer.parseInt(jtNumero.getText());
        
        try{
            Fornecedor fornecedor = new Fornecedor();
            
            fornecedor.setIdFornecedor(id);
            fornecedor.setCnpj(cnpj);
            fornecedor.setNome(nome);
            fornecedor.setTelefone(telefone);
            fornecedor.setEmail(email);
            fornecedor.setBairro(bairro);
            fornecedor.setRua(rua);
            fornecedor.setNumero(numero);
            
            FornecedorDAO dao = new FornecedorDAO();
            dao.editar(fornecedor);
            
            JOptionPane.showMessageDialog(null, "Dados editados com sucesso.");
            Listar();
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro ao editar os dados."+ e);
        }
    }//GEN-LAST:event_jtEditarActionPerformed

    private void jtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtExcluirActionPerformed
        try {
            Fornecedor fornecedor = new Fornecedor();
            
            fornecedor.setIdFornecedor(Integer.parseInt(jtID.getText()));
                        
            FornecedorDAO dao = new FornecedorDAO();
            dao.excluir(fornecedor);
            
            JOptionPane.showMessageDialog(null, "Dados excluidos com sucesso.");
            Listar();
            
            jtCnpj.setText("");
            jtNome.setText("");
            jtTelefone.setText("");
            jtEmail.setText("");
            jtBairro.setText("");
            jtRua.setText("");
            jtNumero.setText("");
            jtID.setText("null");
        
        
        } catch(Exception e ){
            JOptionPane.showMessageDialog(null, "Erro ao excluir os dados.");
        }
    }//GEN-LAST:event_jtExcluirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        menuPrincipal obj = new menuPrincipal();
        obj.setLocationRelativeTo(obj);
        obj.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewFornecedor obj = new ViewFornecedor();
                obj.setLocationRelativeTo(obj);
                obj.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBadicionar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtBairro;
    private javax.swing.JTextField jtCnpj;
    private javax.swing.JButton jtEditar;
    private javax.swing.JTextField jtEmail;
    private javax.swing.JButton jtExcluir;
    private javax.swing.JLabel jtID;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtNumero;
    private javax.swing.JTextField jtRua;
    private javax.swing.JTextField jtTelefone;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
